services:
  # PgAdmin para administración de BD
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@petvet.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - default

  # Microservices
  auth-service:
    build:
      target: AUTH
    ports:
      - "3001:3001"
    networks:
      - default

  appointment-service:
    build:
      target: APPOINTMENTS
    ports:
      - "3002:3002"
    networks:
      - default

  chat-service:
    build:
      target: CHAT
    ports:
      - "3003:3003"
    networks:
      - default

  gateway:
    build:
      target: GATEWAY
    ports:
      - "3000:3000"
    depends_on:
      - auth-service
      - appointment-service
      - chat-service
    networks:
      - default
    

volumes:
  auth_data:
  appointment_data:
  chat_data:
  redis_data:
  pgadmin_data:

networks:
  default:
    name: petvet-network
    driver: bridge
