services:
  auth-db:
      image: postgres:15
      environment:
        POSTGRES_DB: auth_db
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
      ports:
        - "5432:5432"
      volumes:
        - auth_data:/var/lib/postgresql/data
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 10s
        timeout: 5s
        retries: 5
      networks:
        - default

    # Base de datos para Appointment Service
    appointment-db:
      image: postgres:15
      environment:
        POSTGRES_DB: appointment_db
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
      ports:
        - "5433:5432"
      volumes:
        - appointment_data:/var/lib/postgresql/data
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 10s
        timeout: 5s
        retries: 5
      networks:
        - default

    # Base de datos para Chat Service
    chat-db:
      image: postgres:15
      environment:
        POSTGRES_DB: chat_db
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
      ports:
        - "5434:5432"
      volumes:
        - chat_data:/var/lib/postgresql/data
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 10s
        timeout: 5s
        retries: 5
      networks:
        - default

    # Redis para caching y sessions
    redis:
      image: redis:7-alpine
      ports:
        - "6379:6379"
      volumes:
        - redis_data:/data
      networks:
        - default
volumes:
  auth_data:
  appointment_data:
  chat_data:
  redis_data:
  pgadmin_data: