name: Pet-Vet CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  NODE_VERSION: '18'

jobs:
  # Job for linting and building backend services
  lint-and-build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        service: [gateway, auth-service, appointment-service, chat-service]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install root dependencies
      run: npm ci

    - name: Install service dependencies
      run: |
        cd apps/${{ matrix.service }}
        npm ci

    - name: Run linting
      run: |
        cd apps/${{ matrix.service }}
        npm run lint

    - name: Build service
      run: |
        cd apps/${{ matrix.service }}
        npm run build

  # Job for linting and building frontend
  lint-and-build-frontend:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install root dependencies
      run: npm ci

    - name: Install frontend dependencies
      run: |
        cd apps/frontend
        npm ci

    - name: Run linting
      run: |
        cd apps/frontend
        npm run lint

    - name: Build frontend
      run: |
        cd apps/frontend
        npm run build
